name: CI to Docker Hub

on:
  push:
    branches: [ main ]


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    
    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    - name: Build and push
      run: |
        docker buildx build \
        --push --tag azrael783/tor-socks-proxy:latest --platform linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64 .
